#!/usr/bin/env python3
"""demo0-v2 camera tuning GUI (no ROS / no torch — just OpenCV + v4l2).

Opens the ZED (UVC) live, gives trackbars for the V4L2 controls that matter for
STEREO DEPTH quality, and shows — side by side — the rectified-ish left image and a
TEXTURE-PASS overlay: the pixels that have enough local gradient to give the depth
filter a trustworthy match (green = kept, red-dimmed = would become a depth hole).
Crank sharpness / contrast / gamma and watch which surfaces "light up" with texture.

The ZED can only be opened by ONE process, so quit this before running a demo.
Press 's' to SAVE the current controls to demo0-v2/cam_settings.conf; the autoexplore
script sources that and applies it (via v4l2-ctl) right before it opens the camera.

Run (conda lerobot-new — needs cv2 + numpy only):
  python demo0-v2/cam_tune.py                # auto-detect ZED /dev/videoN
  python demo0-v2/cam_tune.py --dev 4        # force device index
Keys:  s = save settings   r = reset to defaults   q / Esc = quit
"""
import os, sys, argparse, subprocess, numpy as np, cv2

HERE = os.path.dirname(os.path.abspath(__file__))
SETTINGS = os.path.join(HERE, "cam_settings.conf")
# name -> (v4l2 control, min, max, default). Only depth-relevant controls.
CTRLS = [
    ("sharpness",  "sharpness",  0,   8,   6),   # edges -> texture for stereo matching
    ("contrast",   "contrast",   0,   8,   6),   # stronger gradients -> better matches
    ("brightness", "brightness", 0,   8,   4),
    ("gamma",      "gamma",      1, 500, 140),   # lift shadows (dark objects get detail)
    ("gain",       "gain",       0,   8,   5),   # only brightness lever (no manual exposure)
]
TEX_MAX = 40   # trackbar range for the texture threshold preview


def detect_dev():
    try:
        out = subprocess.check_output(["v4l2-ctl", "--list-devices"], text=True, stderr=subprocess.DEVNULL)
    except Exception:
        return 0
    lines = out.splitlines()
    for i, l in enumerate(lines):
        if "ZED" in l:
            for j in range(i + 1, min(i + 4, len(lines))):
                m = lines[j].strip()
                if m.startswith("/dev/video"):
                    return int(m.replace("/dev/video", ""))
    return 0


def set_ctrl(dev, ctrl, val):
    subprocess.run(["v4l2-ctl", "-d", f"/dev/video{dev}", f"--set-ctrl={ctrl}={val}"],
                   stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


def load_saved():
    vals = {}
    if os.path.exists(SETTINGS):
        for l in open(SETTINGS):
            l = l.strip()
            if l.startswith("V4L2_CTRLS="):
                body = l.split("=", 1)[1].strip().strip('"')
                for kv in body.split(","):
                    if "=" in kv:
                        k, v = kv.split("=")
                        try: vals[k] = int(v)
                        except ValueError: pass
    return vals


def save(dev, cur):
    body = ",".join(f"{c}={cur[name]}" for name, c, *_ in CTRLS)
    with open(SETTINGS, "w") as f:
        f.write("# demo0-v2 ZED camera settings (generated by cam_tune.py)\n")
        f.write("# applied by demo0_autoexplore.sh before opening the camera\n")
        f.write(f'V4L2_CTRLS="{body}"\n')
    print(f">>> saved -> {SETTINGS}\n    V4L2_CTRLS=\"{body}\"")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dev", type=int, default=None, help="ZED /dev/video index (auto if omitted)")
    ap.add_argument("--width", type=int, default=1344, help="side-by-side capture width (VGA=1344)")
    ap.add_argument("--height", type=int, default=376)
    args = ap.parse_args()
    dev = args.dev if args.dev is not None else detect_dev()
    print(f">>> ZED on /dev/video{dev}")

    cap = cv2.VideoCapture(dev, cv2.CAP_V4L2)
    cap.set(cv2.CAP_PROP_FOURCC, cv2.VideoWriter_fourcc(*"MJPG"))
    cap.set(cv2.CAP_PROP_FRAME_WIDTH, args.width)
    cap.set(cv2.CAP_PROP_FRAME_HEIGHT, args.height)
    if not cap.isOpened():
        print("!! cannot open camera (is a demo still running? try bash utils/lekiwi_cleanup.sh)")
        sys.exit(1)

    win = "cam_tune  (left | texture-pass)   s=save r=reset q=quit"
    cv2.namedWindow(win, cv2.WINDOW_NORMAL)
    saved = load_saved()
    cur = {}
    for name, ctrl, lo, hi, dflt in CTRLS:
        v = saved.get(ctrl, dflt)
        cur[name] = v
        cv2.createTrackbar(name, win, v, hi, lambda x, c=ctrl: set_ctrl(dev, c, x))
        set_ctrl(dev, ctrl, v)
    cv2.createTrackbar("tex_thresh", win, 11, TEX_MAX, lambda x: None)

    while True:
        ok, frame = cap.read()
        if not ok or frame is None:
            continue
        W = frame.shape[1] // 2
        left = frame[:, :W]
        # texture = mean Sobel-gradient magnitude in a 7x7 window (same as depth filter)
        gray = cv2.cvtColor(left, cv2.COLOR_BGR2GRAY)
        gx = cv2.Sobel(gray, cv2.CV_32F, 1, 0, ksize=3)
        gy = cv2.Sobel(gray, cv2.CV_32F, 0, 1, ksize=3)
        texture = cv2.boxFilter(cv2.magnitude(gx, gy), -1, (7, 7))
        tex_thresh = cv2.getTrackbarPos("tex_thresh", win)
        keep = texture >= tex_thresh
        cov = 100.0 * keep.mean()
        # overlay: keep -> greenish, drop -> dark red (these become depth holes)
        ov = left.copy()
        ov[~keep] = (0.35 * ov[~keep] + np.array([0, 0, 70])).astype(np.uint8)
        ov[keep] = (0.6 * ov[keep] + np.array([0, 90, 0])).astype(np.uint8)
        for name in cur:  # refresh cur from trackbars
            cur[name] = cv2.getTrackbarPos(name, win)
        cv2.putText(ov, f"depth-valid ~{cov:4.1f}%  (tex>={tex_thresh})", (8, 24),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 255, 255), 2)
        view = np.hstack([left, ov])
        cv2.imshow(win, view)
        k = cv2.waitKey(30) & 0xFF
        if k in (ord('q'), 27):
            break
        elif k == ord('s'):
            save(dev, cur)
        elif k == ord('r'):
            for name, ctrl, lo, hi, dflt in CTRLS:
                cv2.setTrackbarPos(name, win, dflt); set_ctrl(dev, ctrl, dflt)
    cap.release(); cv2.destroyAllWindows()


if __name__ == "__main__":
    main()
